nodes = [
  {:hostname => "pacemaker1", :ip => "192.168.66.11"},
  {:hostname => "pacemaker2", :ip => "192.168.66.12"},
  {:hostname => "pacemaker3", :ip => "192.168.66.13"}
]

$script = <<SCRIPT
  yum -y install pcs pacemaker httpd
  setenforce 0
  cat /vagrant/hosts > /etc/hosts
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_check_update = false
  config.vbguest.auto_update = false

  nodes.each do |node|
    config.vm.define node[:hostname] do |nodeconfig|
      nodeconfig.vm.hostname = node[:hostname] + ".cs"
      nodeconfig.vm.network :private_network, ip: node[:ip]
      nodeconfig.vm.provider :virtualbox do |vb|
        vb.memory = "1024"
        vb.cpus = "1"
      end
    end
  end

  config.vm.provision "shell", inline: $script
end