script = <<EOF
cat <<MARIADB > /etc/yum.repos.d/mariadb.repo
[mariadb]
name = MariaDB
baseurl = http://yum.mariadb.org/10.1/centos7-amd64
gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
gpgcheck=1
MARIADB
setenforce 0
yum -y install haproxy keepalived MariaDB-server MariaDB-client MariaDB-compat galera socat jemalloc vim net-tools
cat /vagrant/hosts > /etc/hosts
EOF


nodes = [
    { :hostname => "haproxy1", :ip => "192.168.66.11", :script => script},
    { :hostname => "haproxy2", :ip => "192.168.66.12", :script => script}    
]

Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"
    config.vbguest.auto_update = false
    nodes.each do |node|
        config.vm.define node[:hostname] do |nodeconfig|
            nodeconfig.vm.hostname = node[:hostname] + ".cs"
            nodeconfig.vm.network :private_network, ip: node[:ip]
            nodeconfig.vm.provider :virtualbox do |vb|
                vb.cpus=1
                vb.memory=1024
            end
            nodeconfig.vm.provision :shell, inline: node[:script]
        end
    end
end